.github/workflows/cd.yml, .github/workflows/ci-lint.yml, Dockerfile
close #3 
ECR, Lambda, EventBridge를 사용해 Continuous Deployment를 구축했습니다.
=> 🔀 :: (#3) CI/CD 구축

.github/workflows/ci-lint.yml
=> 🔀 :: (#8) CI 수정

application-domain/build.gradle, application-domain/src/main/java/io/github/v1serviceapplication/annotation/Aggregate.java, application-domain/src/main/java/io/github/v1serviceapplication/annotation/DomainService.java, application-domain/src/main/java/io/github/v1serviceapplication/annotation/Spi.java, application-domain/src/main/java/io/github/v1serviceapplication/extensionapply/ExtensionApply.java, application-domain/src/main/java/io/github/v1serviceapplication/picnicapply/PicnicApply.java, application-domain/src/main/java/io/github/v1serviceapplication/stayapply/StayApply.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/StudyRoom.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmealapply/WeekendMealApply.java, build.gradle
=> 🔀 :: (#10) domain model 작성

application-infrastructure/build.gradle, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/extensionapply/ExtensionApply.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicapply/PicnicApply.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stayapply/StayApply.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/StudyRoom.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealapply/WeekendMealApply.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/entity/BaseUUIDEntity.java, application-infrastructure/src/main/resources/application.yml
=> 🔀 :: (#4) entity 작성

application-infrastructure/build.gradle, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/config/QuerydslConfig.java
=> 🔀 :: (#13) querydsl 세팅

.github/CODEOWNERS
=> 🔀 :: (#15) CODEOWNERS 추가

.github/workflows/ci-lint.yml, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/config/FilterConfig.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorAttribute.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/GlobalErrorCode.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/AttributeConvertFailedException.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/BadRequestException.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/GlobalException.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/NotFoundException.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/UnexpectedException.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/handler/ErrorResponse.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/handler/ExceptionHandlerFilter.java, build.gradle
=> 🔀 :: (#17) Filter 설정

application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/extensionapply/domain/ExtensionApply.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicapply/domain/PicnicApply.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stayapply/domain/StayApply.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/StudyRoom.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealapply/domain/WeekendMealApply.java
=> 🔀 :: (#29) 아키텍처 리팩토링

application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/handler/GlobalExceptionHandler.java
=> 🔀 :: (#22) ExceptionHandler 작성

.github/CODEOWNERS
설정에 문제가 있어 다시 설정합니다.
close #37
=> 🔀 :: (#37) CODEOWNERS

application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryStudyRoomRepository.java, application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java, build.gradle
=> 🔀 :: (#35) 테스트 환경 구축

application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryStudyRoomRepository.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/api/dto/response/StudyRoomElement.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/spi/dto/StudyRoomModel.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/vo/StudyRoomVO.java
=> 🔀 :: (#50) 자습실 목록 Api 반환값 수정

application-domain/src/main/java/io/github/v1serviceapplication/picnic/Picnic.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/Stay.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/StudyRoom.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/extension/Extension.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/WeekendMeal.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/PicnicEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/StayEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/ExtensionEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/entity/BaseEntity.java, application-infrastructure/src/main/resources/application.yml
=> 🔀 :: (#49) 신청 Entity 수정

.github/workflows/stg-build.yml
=> 🔀 :: (#41) CD

application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java, application-infrastructure/build.gradle, application-infrastructure/src/main/java/io/github/v1serviceapplication/V1ServiceApplicationApplication.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/InternalServerErrorException.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/JwtInvalidSignatureException.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/JwtTokenExpiredException.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/facade/UserFacade.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/FilterConfig.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/WebConfig.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/jwt/JwtParser.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/jwt/TokenFilter.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/property/JwtProperty.java, application-infrastructure/src/main/resources/application.yml
=> 🔀 :: (#54) jwt 설정

application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/api/ApplyStay.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/service/ApplyStayImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayRepositorySpi.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/PicnicEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/code/StayStatusCode.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/StayEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/mapper/StayMapper.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/dto/request/ApplyStayRequest.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/exception/ConvertFailedException.java
=> 🔀 :: (#24) 잔류 신청 API

build.gradle
=> 🔀 :: (#60) build.gradle jar option

application-infrastructure/src/main/java/io/github/v1serviceapplication/V1ServiceApplicationApplication.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/entity/BaseEntity.java
=> 🔀 :: (#59) base Entity 리팩토링

application-infrastructure/src/main/resources/application.yml
=> 🔀 :: (#67) url prefix 수정

application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorHandlingFilter.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/FilterConfig.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
=> 🔀 :: (#64) ErrorHandlingFilter 등록

application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
=> 🔀 :: (#70) security 설정 추가

application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java, application-domain/src/main/java/io/github/v1serviceapplication/error/StayNotFoundException.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/api/QueryStayStatus.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/api/dto/response/QueryStayStatusResponse.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/service/QueryStayStatusImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayRepositorySpi.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/StayEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepository.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
=> 🔀 :: (#57) 잔류 상태 조회 API

application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/ApplyWeekendPicnic.java, application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/dto/ApplyWeekendPicnicDomainRequest.java, application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/ApplyWeekendPicnicImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/picnic/spi/PicnicRepositorySpi.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/PicnicConfig.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/mapper/PicnicMapper.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/PicnicController.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/dto/request/ApplyWeekendPicnicRequest.java
=> 🔀 :: (#27) 주말 외출 신청 API

application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/api/PostWeekendMeal.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/service/PostWeekendMealImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/spi/PostWeekendMealRepositorySpi.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/WeekendMealConfig.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/CustomWeekendMealRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/mapper/WeekendMealMapper.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/WeekendMealController.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/dto/request/PostWeekendMealRequest.java
=> 🔀 :: (#25) 주말 급식 신청 API

application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
=> 🔀 :: (#79) test code

.github/workflows/prod-build.yaml, .github/workflows/stg-build.yml
=> 🔀 :: (#84) cd 파일 수정

application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
=> 🔀 :: (#86) UUID 통일

application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorHandlingFilter.java
=> 🔀 :: (#90) Exception Handling 

application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
=> 🔀 :: (#98) queryStayStatus 이번 주 값으로

application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
=> 🔀 :: (#100) 사소한 버그

application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryStudyRoomRepository.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/api/QueryStudyRoomStatus.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomStatusImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/spi/StudyRoomRepositorySpi.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/StudyController.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/dto/response/StudyRoomStatusResponse.java
=> 🔀 :: (#102) 자습실 신청 상태 조회 Api

application-infrastructure/src/main/java/io/github/v1serviceapplication/global/role/UserRole.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/AuthenticationFilter.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/FilterConfig.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenFilter.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
=> 🔀 :: (#104) config authorization/authentication

application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/WeekendMeal.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/WeekendMealApply.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/exception/WeekendMealNotFoundException.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/api/PostWeekendMealApply.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/service/PostWeekendMealApplyImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/spi/PostWeekendMealApplyRepositorySpi.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/queryweekendmeal/api/QueryWeekendMeal.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/queryweekendmeal/service/QueryWeekendMealImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/queryweekendmeal/spi/QueryWeekendMealRepositorySpi.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealApplyEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/CustomWeekendMealApplyRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/CustomWeekendMealRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/mapper/WeekendMealApplyMapper.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/mapper/WeekendMealApplyMapperImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/mapper/WeekendMealMapper.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/WeekendMealController.java
=> 🔀 :: (#109) 주말급식 조회 Api 작성

application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java, application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/ApplyWeekendPicnicImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/service/PostStudyRoomImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/poststudyroom/spi/PostStudyRoomRepositorySpi.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/exception/WeekendMealApplyNotFoundException.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/service/PostWeekendMealApplyImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/postweekendmeal/spi/PostWeekendMealApplyRepositorySpi.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/WeekendMealApplyEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/CustomWeekendMealApplyRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/domain/repository/WeekendMealApplyRepository.java
=> 🔀 :: (#111) 주말급식 신청 Api 수정

application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/AuthenticationFilter.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/FilterConfig.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
=> 🔀 :: (#108) filter config

application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/AuthenticationFilter.java
=> 🔀 :: (#119) authentication filter refactoring

application-domain/src/main/java/io/github/v1serviceapplication/stay/api/SetDefaultStay.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/service/SetDefaultStayImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayRepositorySpi.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/dto/request/SetDefaultStayRequest.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
close #118 
유저 회원가입 시 신청 쪽 테이블의 디폴트 값을 넣어주는 api 입니다.
=> 🔀 :: (#118) 유저 회원가입

application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryStudyRoomRepository.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/StudyRoom.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/api/QueryStudyRoom.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/spi/StudyRoomRepositorySpi.java, application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/StudyRoomEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/StudyController.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorHandlingFilter.java
=> 🔀 :: (#122) 자습실 목록 Api 수정

.github/workflows/prod-build.yaml, .github/workflows/stg-build.yml
=> 🔀 :: (#124) Actions ECR 이전

application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryStudyRoomRepository.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/StudyRoom.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/api/QueryStudyRoom.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/querystudyroom/spi/StudyRoomRepositorySpi.java, application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/StudyRoomEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/StudyController.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/error/ErrorHandlingFilter.java
Reverts team-xquare/v1-service-application#123
=> Revert "🔀 :: (#122) 자습실 목록 Api 수정"

application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/PicnicApi.java, application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/PicnicController.java
=> 🔀 :: Picnic 도메인 리팩토링

application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java
=> 🔀 :: (#150) 잔류 신청 API 응답코드 수정

application-domain/src/main/java/io/github/v1serviceapplication/stay/api/StayApi.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/service/StayApiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/StayController.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/dto/request/SignupSettingRequest.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
=> ♻️ :: 로직 수정

application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
=> 🔀 :: (#159) 자습실 신청 일자 버그

application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java, application-infrastructure/build.gradle, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/FeignClientErrorDecoder.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/FeignConfig.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/error/FeignBadRequestException.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/error/FeignExpiredTokenException.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/error/FeignForbiddenException.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/error/FeignUnAuthorizedException.java
=> 🔀 :: (#162) OpenFeign 설정

application-domain/src/main/java/io/github/v1serviceapplication/stubs/InMemoryQueryStudyRoomRepository.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/service/StudyRoomApiImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/spi/QueryStudyRoomRepositorySpi.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/spi/StudyRoomQueryExtensionRepositorySpi.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/spi/StudyRoomUserFeignSpi.java, application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/repository/CustomExtensionRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/repository/CustomStudyRoomRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/client/UserClient.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/client/UserClientImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/client/dto/response/UserInfoResponse.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/feign/client/dto/response/UserInfoResponseElement.java, application-infrastructure/src/main/resources/application.yml
=> 🔀 :: (#161) 자습실 학생 리스트 기능 제작

application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/exception/AlreadyExistsStayException.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/service/StayApiImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/spi/StayRepositorySpi.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
=> 🔀 :: (#167) 잔류 버그

application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/domain/repository/CustomStudyRoomRepositoryImpl.java
=> 🔀 :: (#171) 자습실 신청 상태 조회 Api OSIV 영향

application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/api/StudyRoomApi.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/exception/ExtensionNotFoundException.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/exception/InCorrectStudyRoomIdException.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/service/StudyRoomApiImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/spi/StudyRoomPostExtensionRepositorySpi.java, application-domain/src/main/java/io/github/v1serviceapplication/studyroom/spi/StudyRoomQueryExtensionRepositorySpi.java, application-domain/src/test/java/io/github/v1serviceapplication/studyroom/querystudyroom/service/QueryStudyRoomImplTest.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/extension/domain/repository/CustomExtensionRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/mapper/ExtensionMapper.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/presentation/StudyController.java
=> 🔀 :: (#169) 자습실 신청 취소 Api

application-domain/src/main/java/io/github/v1serviceapplication/studyroom/service/StudyRoomApiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/mapper/ExtensionMapper.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/studyroom/mapper/ExtensionMapperImpl.java
=> 🔀 :: (#173) 자습실 신청 취소 Api

application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/WebConfig.java
=> 🔀 :: (#175) CORS credentials

application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/picnic/spi/PicnicRepositorySpi.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java
=> 🔀 :: (#181) 주말외출 신청 하나라도 신청되어 있다면 에러

application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java, application-domain/src/main/java/io/github/v1serviceapplication/error/InvalidPicnicApplicationTimeException.java, application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
=> 183-외출 시작시간이랑 도착시간이 역전되있을 때 예외처리 추가

application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/StayStatusExcel.java
=> 🔀 :: (#185) 엑셀 디자인 꾸미기

application-domain/src/main/java/io/github/v1serviceapplication/studyroom/service/StudyRoomApiImpl.java
=> 🔀 :: (#201) 자습실 신청 시간 제한 조건 수정

application-domain/src/main/java/io/github/v1serviceapplication/stay/service/StayApiImpl.java
stayList는 권한 구분 없이 tbl_stay_apply테이블에 있는 모든 값을 가져오는데 studentList는 UserFeign요청으로 STU권한을 가진 사람들만 조회를 해서 stay.userId로 studentList로 값을 찾을 때 선생님들은 조회가 안되서 NPE오류가 나게 되어서 Exception처리를 추가했습니다
=> 🔀 :: (#23) Exception 코드 추가

application-domain/src/main/java/io/github/v1serviceapplication/picnic/Picnic.java, application-domain/src/main/java/io/github/v1serviceapplication/picnic/api/PicnicApi.java, application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java, application-domain/src/main/java/io/github/v1serviceapplication/picnic/spi/PicnicRepositorySpi.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/PicnicEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/mapper/PicnicMapperImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/AdminPicnicController.java
사감 선생님이 외출 복귀 기능을 원하시지 않으셔서 복귀 시간 칼럼과 외출 복귀 API를 삭제했습니다.
=> 🔀 :: (#42) 외출 복귀 기능 삭제

application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
열 너비를 늘리고 학번순으로 정렬하는 것을 추가했습니다
=> 🔀 :: (#44) 주말 외출 리스트 엑셀 API 수정

application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/WeekendMealCheck.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/exception/WeekendMealCheckNotFoundException.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/spi/PostWeekendMealCheckRepositorySpi.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/spi/QueryWeekendMealCheckRepositorySpi.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/WeekendMealApi.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/service/WeekendMealApiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/AdminWeekendMealController.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/dto/PostWeekendMealCheckRequest.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/domain/WeekendMealCheckEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/domain/repository/CustomWeekendMealCheckRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/domain/repository/WeekendMealCheckRepository.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/mapper/WeekendMealCheckMapper.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/mapper/WeekendMealCheckMapperImpl.java
주말 급식과 관련하여 학생이 잘못 신청 하였을 때 등의 책임문제가 발생할 수 있어서 학생들의 주말 급식 신청을 담임 선생님이 확인이 필요해서 확인 API를 작성하게 되었습니다. 담임 선생님이 확인여부 취소가 가능하도록 만들었습니다.
=> 🔀 :: (#44) 주말급식 선생님 확인 API

application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/WeekendMealApi.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/service/WeekendMealApiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/notification/scheduler/NotificationScheduler.java
선생님이 신청 날부터 신청불가 전까지 매일 아침 8시 20분에 알림
=> 🔀 :: (#158) 주말 급식 신청 알림

application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/WeekendMealCheck.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeakcheck/spi/QueryWeekendMealCheckRepositorySpi.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/WeekendMealApi.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/dto/WeekendMealCheckStatusResponse.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/api/dto/WeekendMealListResponse.java, application-domain/src/main/java/io/github/v1serviceapplication/weekendmeal/service/WeekendMealApiImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmeal/presentation/AdminWeekendMealController.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/domain/WeekendMealCheckEntity.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/domain/repository/CustomWeekendMealCheckRepositoryImpl.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/weekendmealcheck/mapper/WeekendMealCheckMapperImpl.java
- 담임선생님이 주말급식 확인을 하면 해당 반 학생들은 주말급식 신청이 불가능하게 변경하였습니다.
- 담임 선생님 확인 여부를 주말급식 학생 리스트에서 반환하는 API로 따로 분리하였습니다
=> 🔀 :: (#149) 주말급식 신청 API 수정 및 주말급식 담임 선생님 확인 API로 분리

application-domain/src/main/java/io/github/v1serviceapplication/notification/NotificationSpi.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/notification/NotificationAdapter.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/notification/dto/DomainSendGroupMessageRequest.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/notification/dto/DomainSendMessageRequest.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/notification/dto/DomainSendSpecificGroupRequest.java, application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/notification/scheduler/NotificationScheduler.java
notification 쪽에서 json을 topic으로 받는데 category로 json을 보내는 type mismatch 에러 해결
- notiication에서 topic으로 category로 찾기 때문에 application을 수정하는 쪽으로 변경하였습니다
=> 🔀 :: (#179) topic으로 변경

application-domain/src/main/java/io/github/v1serviceapplication/error/ErrorCode.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/exception/CanNotStayApplyException.java, application-domain/src/main/java/io/github/v1serviceapplication/stay/service/StayApiImpl.java
- 잔류 신청이 가능한 시간은 목요일 오후 8시30분부터 오후 11시까지 입니다. 해당 시간에 맞춰 요청 시간을 확인하는 메소드를 추가했습니다.
=> 🔀 :: (#170) 잔류 신청 요청 시간 확인 메소드 추가

application-domain/src/main/java/io/github/v1serviceapplication/stay/service/StayApiImpl.java
- 요구사항 -> 목요일 22시 ~ 일요일 0시까지 잔류 신청 변경 제한 
위에 따라 조건문을 수정했습니다.
=> 🔀 :: (#187) 잔류 신청 조건문 수정
